### ISSUE TITLE
后台所有的更新不可用，提示成功，但是没有成功？？？

### ISSUE THREAD

**Issue by oweson** [zhangyd-c/OneBlog#14]
是不是缓存？？？

**Comment by zhangyd-c** [comment]
去http://dblog-admin.zhyd.me中试试，能复现吗， 这是最新代码部署的

**Comment by oweson** [comment]
好的


 
---原始邮件---
发件人: "yadong.zhang"<notifications@github.com>
发送时间: 2019年7月1日(星期一) 晚上8:40
收件人: "zhangyd-c/OneBlog"<OneBlog@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"皮皮程"<570347720@QQ.com>;
主题: Re: [zhangyd-c/OneBlog] 后台所有的更新不可用，提示成功，但是没有成功？？？ (#14)



去http://dblog-admin.zhyd.me中试试，能复现吗， 这是最新代码部署的

**Comment by wenjunzhangp** [comment]
我现在也碰到这个问题了，同学你们后来是怎么解决的呀。
