### ISSUE TITLE
作者你好，反馈几个问题

### ISSUE THREAD

**Issue by wly1435076663** [zhangyd-c/OneBlog#15]
1、在后台点击发布文章，效果是新增文章并发表，但是在富文本框中带出一些其它文章的文字
2、文章发布时，标签经常无法点击，导致文章编辑好之后无法发布或者保存草稿

**Comment by zhangyd-c** [comment]
第二个问题已经修复，请更新代码。
第一个问题，md编辑器默认是有缓存的， 当你发布成功后缓存中的内容会自动清理掉，反之，如果你在新增文章的时候，编辑器里写入了内容，但是并没有点击发布，那么当你刷新的时候，会自动从缓存中获取未发布的内容。

**Comment by wly1435076663** [comment]
第二个问题我本地调试了一下发现是延时太短造成的，第一个问题我这边缓存有点奇怪，直接进页面点新增文章，有时候会把已发布的信息带出来，不是编辑之后没发布带出来。就是刚启动项目，然后进入页面，增加文章就带出缓存了

**Comment by zhangyd-c** [comment]
嗯， 延迟低那个我调了， 缓存这个，我本地没测出来这个问题， 文章发布完成后会自动清除缓存。 缓存只在你修改了编辑器内容，但是没点保存（或者没手动清除缓存）时，再次打开就会显示。

**Comment by wly1435076663** [comment]
> 嗯， 延迟低那个我调了， 缓存这个，我本地没测出来这个问题， 文章发布完成后会自动清除缓存。 缓存只在你修改了编辑器内容，但是没点保存（或者没手动清除缓存）时，再次打开就会显示。
