### ISSUE TITLE
您好，有时候更新操作实际上是不成功的

### ISSUE THREAD

**Issue by 1571312541** [zhangyd-c/OneBlog#16]
提示更新成功，但实际上是失败的，例如：
1、在系统设置中，先更新基本信息的站点简介，更新成功，再不刷新当前页面的情况下，编辑登陆下的登陆重试次数，编辑完后提交保存，提示成功，但实际上，并未成功，没有进行更新操作，但会记录修改系统配置的日志。
2、在权限管理中，角色管理，编辑角色信息提示成功，实际未成功，但会记录编辑角色配置的日志。实际执行的sql是 
Preparing: UPDATE sys_role SET id = id,update_time = ? WHERE id = ? 
Parameters: 2019-08-12 10:52:43.904(Timestamp), null
3、在权限管理中，资源管理，和第二个是一个问题，编辑提示成功，实际未成功
4、在用户列表中，用户列表，和第二个是一个问题，编辑提示成功，实际未成功
5、文章搬运工，封面图未转换成指定地址，依旧是原地址
6、网站管理中，更新日志中，和第二个是一个问题，编辑提示成功，实际未成功
7、网站管理中，公告管理中，和第二个是一个问题，编辑提示成功，实际未成功
8、网站管理中，友情链接中，和第二个是一个问题，编辑提示成功，实际未成功
8、网站管理中，模板管理中，和第二个是一个问题，编辑提示成功，实际未成功
9、文章管理中，文章列表中，推送到百度站长平台功能，当推送提示失败时，信息“site error”，再次点击推送按钮，提示失败，这时信息是“请至少选择一条记录”，实际上是选择了数据，应该再次提示信息“site error”
10、文章管理中，标签列表中，和第二个是一个问题，编辑提示成功，实际未成功
11、文章管理中，分类列表中，和第二个是一个问题，编辑提示成功，实际未成功
目前遇到这些问题，好像所有编辑功能有问题，是我克隆代码问题嘛？望作者回复，谢谢。
同时，感谢作者开源这么好项目。

**Comment by wenjunzhangp** [comment]
同学，你这个后来是咋解决的呀
