### ISSUE TITLE
貌似忘记添加日志工具了

### ISSUE THREAD

**Issue by zkydrx** [zhangyd-c/OneBlog#2]
![snipaste_2018-09-15_23-21-36](https://user-images.githubusercontent.com/19487290/45587859-2d110080-b93e-11e8-8575-25fc59bacfcb.png)

**Comment by zhangyd-c** [comment]
@zkydrx 本项目使用的lombok插件，需要给ide安装该插件。

参考这个文档[http://dblog-docs.zhyd.me/FAQ/](http://dblog-docs.zhyd.me/FAQ/)

**Comment by zkydrx** [comment]
好的。
