### ISSUE TITLE
博客id错误问题

### ISSUE THREAD

**Issue by xcxzzx-1** [zhangyd-c/OneBlog#6]
博客id大于999以后，上一篇和下一篇的id错误。例如1234 会变成1,234 
点击以后，后台出错

‘’‘
2019-05-19 22:32:54 [com.zyd.blog.framework.advice.ExceptionHandleController:72] ERROR - url参数异常，请检查参数类型是否匹配！
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "6,873"
’‘’

‘’‘
Caused by: java.lang.NumberFormatException: For input string: "6,873"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
’‘’

**Comment by xcxzzx-1** [comment]
[上一篇](https://github.com/zhangyd-c/OneBlog/blob/a5a81ef70229d208c652a77e655ccf7248ca5878/blog-web/src/main/resources/templates/article.ftl#L100)
[下一篇](https://github.com/zhangyd-c/OneBlog/blob/a5a81ef70229d208c652a77e655ccf7248ca5878/blog-web/src/main/resources/templates/article.ftl#L113)

${val?c}

**Comment by zhangyd-c** [comment]
谢谢修复该问题！
